#!/bin/bash
echo Processor: `uname -p | sed 's/_\+/ /g'`
echo Memory: `free -g | grep Mem | sed 's/Mem: *\([0-9]\+\) *[0-9]\+ *\([0-9]\+\).*/\2 \/ \1 GB/'`
echo Free disk space on root: `df -h / | grep /dev | awk -F ' ' '{print$4}'`
echo System: `uname -r`
