#!/bin/bash

# 2> /dev/null -- Przekierowanie standardowego wyjscia bledow do czarnej dziury.

x=`du --max-depth=1 2> /dev/null /etc | grep /etc/ | sort -n` 
echo Najmniejszy
echo "$x" | head -1
echo Najwiekszy 
echo "$x" | tail -1

