#!/bin/bash

# 2> /dev/null -- Przekierowanie standardowego wyjscia bledow do czarnej dziury.

x=`du --max-depth=1 2> /dev/null /etc | grep /etc/` 
echo Najmniejszy
echo "$x" | sort -n | head -1
echo Najwiekszy 
echo "$x" | sort -nr | head -1

